### ISSUE TITLE
The login for the admin is glitchy

### ISSUE THREAD

**Issue by geriweitzman** [TomOnTime/phpresourcedir-issues#1]
Hugs Tom,
I logged in to the admin side of the website. When I did, I got this error message:

Error 1044 : Access denied for user 'polylistprodadmn'@'localhost' to database 'polylistProdDB'

The same error persisted when I tried to click on 'Categories,' though it seemed fine with letting me click the link to add a new professional.

Thanks!
Geri

**Comment by TomOnTime** [comment]
That might have happened while I was still making some adjustments.  Let me know if it happens again.

**Comment by geriweitzman** [comment]
Still happening on both BAP and PFP, alas.

**Comment by TomOnTime** [comment]
Ah, now I'm able to reproduce the problem.  Fixed.
