### ISSUE TITLE
On the 'about' page...

### ISSUE THREAD

**Issue by geriweitzman** [TomOnTime/phpresourcedir-issues#10]
Here are a few issues on the http://polyfriendly.org/about.php page:
1. Please add David Wheeler to the list of people in this line under the heading 'Cool directory! To whom should we give thanks?':

"including James Munger, Keith Brown, Jared D, Eric DeRiel, William Slaughter, Ponygroom, and Franklin Veaux."
1. Note the missing apostrophy in the word we're, below:

Have the professionals listed in the directory been "vetted" as being poly-friendly, or as being capable professionally?
Nope - were a small crew of volunteers

-- I notice that both directories have issues with ' and " symbols - I noted this with the word can't in an earlier bug report, and also the BAP directory since the beginning has rejected any practice description blurb that contains one of those characters. I simply have worked around it by editing any submissions that use them, like 'can't' becomes 'cannot.' If there isn't an easy workaround, then please change "were a small crew of volunteers" to "we are a small crew of volunteers" - thanks!

(Although I see that further down in this page they show up fine - "Some are, some aren't, and those of us in the know ain't tellin'." -hmm...)

Thanks,
Geri

**Comment by TomOnTime** [comment]
Fixed
