### ISSUE TITLE
Please change 'bisexuality-aware' to poly-friendly

### ISSUE THREAD

**Issue by geriweitzman** [TomOnTime/phpresourcedir-issues#6]
Where I've asterisked, below - please change bisexuality-aware to poly-friendly - thanks! This is at the header of the directory listings page.

"Click on your state / province / country below. If your state / province / country isn't listed, then we don't yet have any **bisexuality-aware** professionals listed there in this category."

**Comment by TomOnTime** [comment]
Fixed.
