### ISSUE TITLE
Spelling error on the 'joining' page

### ISSUE THREAD

**Issue by geriweitzman** [TomOnTime/phpresourcedir-issues#8]
Hugs Tom,

On the page http://polyfriendly.org/joining.php

If you scroll down, under the question Are all listings automatically accepted?
Note the odd spelling of can't -  may need to change it to cannot:

We canâ€™t accept listings for sexual services given legal concerns.

Thanks!
Geri

**Comment by TomOnTime** [comment]
Fixed. That was a unicode translation error.
