### ISSUE TITLE
Can we change the sample ads link?

### ISSUE THREAD

**Issue by geriweitzman** [TomOnTime/phpresourcedir-issues#9]
On the joining page http://polyfriendly.org/joining.php it says:

Can I see some sample ads before submitting mine?
Sure! All of the ads can be accessed from http://betapolysite.bizone.org/index.php

When I copy-paste the url, it leads to a non-active page. Instead of fixing it, maybe the answer to the question can be:

Sure! Simply scroll through the existing directory listings.

Thanks, Geri

**Comment by TomOnTime** [comment]
Fixed
